# https://script.google.com/macros/s/AKfycbyTdtviLyovBFthbw423r0LoomX9gOjSEsfN2bggm57EXBONdQ/exec

[build]
  functions = 'functions/'

[[redirects]]
  from = '/api/leads'
  to = '/.netlify/functions/postLead'
  status = 200