name: EW Website Build on Push
on: [push]
jobs:
  Build-Push:
    runs-on: ubuntu-latest
    env:
      PUSH_PACKAGES: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      AWS_REGION: us-west-1 # set this to your preferred AWS region, e.g. us-west-1
    steps:
      - run: echo "Running test build for the pushing of branch ${{ github.ref }}"

      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Copy files to S3 bucket
        run: |
          aws s3 ls

      # - if: env.PUSH_PACKAGES != true
      #   run: ${GITHUB_WORKSPACE}/deploy-website.sh -b

      # - if: env.PUSH_PACKAGES == true
      - run: ${GITHUB_WORKSPACE}/deploy-website -bd

      - run: echo "🍏 This job's status is ${{ job.status }}."
