name: EW Website Build on Push
on: [push]
jobs:
  Build-Push:
    runs-on: ubuntu-latest
    env:
      PUSH_PACKAGES: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - run: echo "Running test build for the pushing of branch ${{ github.ref }}"

      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install

      - if: env.PUSH_PACKAGES !== true
        run: bash ./deploy-website -b
      - if: env.PUSH_PACKAGES == true
        run: bash ./deploy-website -bd

      - run: echo "🍏 This job's status is ${{ job.status }}."
